/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

// react-native-vector-icons has no bundled TypeScript declarations.
declare module 'react-native-vector-icons/MaterialIcons' {
  import {Component} from 'react';
  import {TextProps} from 'react-native';
  interface IconProps extends TextProps {
    name: string;
    size?: number;
    color?: string;
  }
  export default class Icon extends Component<IconProps> {}
}